# Generated by Django 4.2.13 on 2026-02-11 18:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('medical', '0001_initial'),
        ('gestion_tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVousType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_defaut', models.IntegerField(default=30)),
                ('couleur', models.CharField(default='#3498db', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Type de rendez-vous',
                'verbose_name_plural': 'Types de rendez-vous',
                'db_table': 'rendez_vous_type',
                'unique_together': {('tenant', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='RendezVousStatut',
            fields=[
                ('statut_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('couleur', models.CharField(choices=[('#2ecc71', 'Vert (Confirmé)'), ('#f39c12', 'Orange (En attente)'), ('#e74c3c', 'Rouge (Annulé)'), ('#3498db', 'Bleu (Planifié)'), ('#95a5a6', 'Gris (Terminé)'), ('#9b59b6', 'Violet (Reporté)')], default='#3498db', max_length=20)),
                ('est_annule', models.BooleanField(default=False)),
                ('est_confirme', models.BooleanField(default=False)),
                ('est_termine', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Statut de rendez-vous',
                'verbose_name_plural': 'Statuts de rendez-vous',
                'db_table': 'rendez_vous_statut',
                'unique_together': {('tenant', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('rendez_vous_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField()),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('raison_annulation', models.TextField(blank=True, null=True)),
                ('rappel_envoye', models.BooleanField(default=False)),
                ('date_rappel', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(db_column='medecin_id', on_delete=django.db.models.deletion.CASCADE, to='medical.medecin')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('statut', models.ForeignKey(db_column='statut_id', on_delete=django.db.models.deletion.CASCADE, to='rendez_vous.rendezvousstatut')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
                ('type', models.ForeignKey(blank=True, db_column='type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rendez_vous.rendezvoustype')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'db_table': 'rendez_vous',
                'ordering': ['date_heure'],
                'indexes': [models.Index(fields=['tenant', 'medecin', 'date_heure'], name='rendez_vous_tenant__852180_idx'), models.Index(fields=['patient', 'date_heure'], name='rendez_vous_patient_823637_idx'), models.Index(fields=['statut', 'date_heure'], name='rendez_vous_statut__28d22a_idx')],
            },
        ),
    ]
