# Generated by Django 4.2.13 on 2026-02-11 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturation', '0001_initial'),
        ('medical', '0001_initial'),
        ('gestion_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifconsultation',
            name='specialite',
            field=models.ForeignKey(db_column='specialite_id', on_delete=django.db.models.deletion.CASCADE, to='medical.specialite'),
        ),
        migrations.AddField(
            model_name='tarifconsultation',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='abonnement',
            field=models.ForeignKey(db_column='abonnement_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.abonnement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='methode',
            field=models.ForeignKey(db_column='methode_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.paiementmethode'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.ForeignKey(db_column='statut_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.paiementstatut'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paiement',
            field=models.OneToOneField(db_column='paiement_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.paiement'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='statut',
            field=models.ForeignKey(db_column='statut_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.invoicestatut'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='essaigratuit',
            name='plan',
            field=models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.plan'),
        ),
        migrations.AddField(
            model_name='essaigratuit',
            name='tenant',
            field=models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='coupontenant',
            name='coupon',
            field=models.ForeignKey(db_column='coupon_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.coupon'),
        ),
        migrations.AddField(
            model_name='coupontenant',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='plans_valides',
            field=models.ManyToManyField(blank=True, to='facturation.plan'),
        ),
        migrations.AddField(
            model_name='abonnementrenouvellement',
            name='abonnement',
            field=models.ForeignKey(db_column='abonnement_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.abonnement'),
        ),
        migrations.AddField(
            model_name='abonnementrenouvellement',
            name='paiement',
            field=models.ForeignKey(db_column='paiement_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.paiement'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='plan',
            field=models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.plan'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='statut',
            field=models.ForeignKey(db_column='statut_id', on_delete=django.db.models.deletion.CASCADE, to='facturation.abonnementstatut'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='tenant',
            field=models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='tarifconsultation',
            unique_together={('tenant', 'specialite', 'date_debut')},
        ),
        migrations.AlterUniqueTogether(
            name='coupontenant',
            unique_together={('coupon', 'tenant')},
        ),
    ]
