# Generated by Django 4.2.13 on 2026-02-11 18:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentCategorie',
            fields=[
                ('categorie_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Catégorie de médicament',
                'verbose_name_plural': 'Catégories de médicaments',
                'db_table': 'medicament_categorie',
                'unique_together': {('tenant', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('medicament_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('forme_pharmaceutique', models.CharField(choices=[('comprime', 'Comprimé'), ('capsule', 'Capsule'), ('sirop', 'Sirop'), ('suspension', 'Suspension'), ('poudre', 'Poudre'), ('creme', 'Crème'), ('pommade', 'Pommade'), ('gel', 'Gel'), ('solution', 'Solution'), ('injectable', 'Injectable'), ('suppositoire', 'Suppositoire'), ('patch', 'Patch'), ('aerosol', 'Aérosol'), ('autre', 'Autre')], default='comprime', max_length=50)),
                ('dosage_standard', models.CharField(blank=True, max_length=100, null=True)),
                ('code_atc', models.CharField(blank=True, max_length=20, null=True)),
                ('dci', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_actuel', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimum', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('necessite_ordonnance', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, db_column='categorie_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_medicaments.medicamentcategorie')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'db_table': 'medicament',
                'indexes': [models.Index(fields=['tenant', 'nom'], name='medicament_tenant__040af9_idx'), models.Index(fields=['categorie'], name='medicament_categor_1c49bb_idx'), models.Index(fields=['actif'], name='medicament_actif_20892e_idx')],
            },
        ),
    ]
