# Generated by Django 4.2.13 on 2025-12-13 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
        ('gestion_tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('rendez_vous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='cree_par_utilisateur',
            field=models.ForeignKey(blank=True, db_column='cree_par_utilisateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medecin',
            name='hopital',
            field=models.ForeignKey(db_column='hopital_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='modifie_par_utilisateur',
            field=models.ForeignKey(blank=True, db_column='modifie_par_utilisateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medecin',
            name='specialite_principale',
            field=models.ForeignKey(blank=True, db_column='specialite_principale_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.specialite'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecin_lie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ligneprescription',
            name='prescription',
            field=models.ForeignKey(db_column='prescription_id', on_delete=django.db.models.deletion.CASCADE, to='medical.prescription'),
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='consultation',
            field=models.ForeignKey(blank=True, db_column='consultation_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.consultation'),
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='medecin_prescripteur',
            field=models.ForeignKey(blank=True, db_column='medecin_prescripteur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_prescrits', to='medical.medecin'),
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='examenmedical',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(db_column='medecin_id', on_delete=django.db.models.deletion.CASCADE, to='medical.medecin'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='rendez_vous',
            field=models.ForeignKey(blank=True, db_column='rendez_vous_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rendez_vous.rendezvous'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='prescription',
            unique_together={('ordonnance', 'medicament')},
        ),
        migrations.AddIndex(
            model_name='medecin',
            index=models.Index(fields=['hopital', 'nom'], name='medecin_hopital_f9180f_idx'),
        ),
        migrations.AddIndex(
            model_name='medecin',
            index=models.Index(fields=['specialite_principale'], name='medecin_special_5d4eed_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['tenant', 'patient'], name='consultatio_tenant__c19453_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['medecin', 'date_consultation'], name='consultatio_medecin_07adf2_idx'),
        ),
    ]
