# Generated by Django 4.2.13 on 2026-02-11 18:55

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('utilisateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('role', models.CharField(choices=[('admin-systeme', 'Administrateur Système'), ('proprietaire-hopital', 'Propriétaire Hôpital'), ('medecin', 'Médecin'), ('infirmier', 'Infirmier'), ('secretaire', 'Secrétaire'), ('personnel', 'Personnel'), ('patient', 'Patient')], default='patient', max_length=50)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('derniere_modification', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateur',
            },
        ),
    ]
